### ISSUE TITLE
can i combine  Restify + node-neo4j-swagger-api

### ISSUE THREAD

**Issue by pangguoming** [tinj/node-neo4j-swagger-api#3]
i am doing a restful project with nodejs , i did not use express, i use Restify, can i combine  Restify and node-neo4j-swagger-api ?

**Comment by flipside** [comment]
You're welcome to try, no idea how much work it would be. 

—
Mat Tyndallfounder & ceo of tinj 

415-562-4628

**Comment by pangguoming** [comment]
thanks
